Repository mautic/user-documentation, pull requests merged in 2024-06, with the labels that each got.

#258 [UX] Change how the ways to implement a form are called
  docs/components/forms.rst
  docs/components/images/forms/embed_form.png
  docs/components/images/forms/embed_form_manual.png
Labels: ready-to-commit, pending-pr-merge

#284 Add docs for webhook queue range mode #13448
  docs/configuration/cron_jobs.rst
Labels: ready-to-commit

#268 Excluding segments from segment emails
  docs/channels/emails.rst
  docs/channels/images/emails/email-excluding-segments.png
Labels: ready-to-commit

#282 Add examples of countries and regions via JSON
  docs/contacts/custom_fields.rst
Labels: ready-to-commit

#267 Docs for 10822
  docs/segments/manage_segments.rst
Labels: ready-to-commit

#272 Change "System Report?" to "Visible for other users"
  docs/reports/reports.rst
Labels: ready-to-commit

#289 Add new command reference #10775
  docs/configuration/command_line_interface.rst
  docs/contacts/custom_fields.rst
Labels: ready-to-commit

#290 DPMMA-1572 clone campaign events
  docs/campaigns/campaign_builder.rst
  docs/campaigns/images/clone-campaign-event.png
  docs/campaigns/images/paste-cloned-event-modal.png
Labels: ready-to-commit

#291 Exclude processed entities
  docs/configuration/cron_jobs.rst
Labels: ready-to-commit

#293 Add user documentation for PR mautic/mautic#13383.
  docs/campaigns/campaign_builder.rst
Labels: ready-to-commit

#294 Docs for 12922
  docs/configuration/cron_jobs.rst
Labels: ready-to-commit

#295 Docs for #12884
  docs/users_roles/managing_roles.rst
Labels: ready-to-commit

#276 Update image for 13478
  docs/components/images/forms/embed_form_manual.png
Labels: blocked

#292 [UX] Reorder administration panel
  docs/marketplace/images/marketplace-list.png
  docs/plugins/images/plugins.png
Labels: pending-pr-merge
