Repository mautic/user-documentation, pull requests merged in 2024-11, with the labels that each got.

#339 Create funding-manifest-urls
  .well-known/funding-manifest-urls
Labels: hacktoberfest-accepted

#340 docs: create new doc for mailchimp plugin app
  docs/plugins/images/plugins-mailchimp-configure.png
  docs/plugins/images/plugins-mailchimp-copy-api-key.png
  docs/plugins/images/plugins-mailchimp-create-api-key-1-and-2.png
  docs/plugins/images/plugins-mailchimp-create-api-key-3a.png
  docs/plugins/images/plugins-mailchimp-create-api-key-3b-and-3c.png
  docs/plugins/mailchimp.rst
Labels: documentation, hacktoberfest-accepted

#332 DPMMA-2831 `dnc_url` token
  docs/channels/emails.rst
Labels: documentation, enhancement, ready-to-commit, hacktoberfest-accepted, Mautic 5

#338 social login guide
  docs/links/Facebook_developer.py
  docs/links/Linkedin_developer.py
  docs/links/X-developer.py
  docs/plugins/images/API_key.png
  docs/plugins/images/Call_back.png
  docs/plugins/images/adding_social_login.png
  docs/plugins/social_login.rst
Labels: hacktoberfest-accepted
